### PR TITLE
failing test case

### PR DESCRIPTION
**Pull request by slang800**
Bash 4.3 (and minimatch 0.2.9) performs no expansion on `{},b}.h`, but this library converts it to `}.h` and `b.h`.

I ran into this problem while trying to get the latest version of minimatch to pass the tests in https://github.com/editorconfig/editorconfig-core-test.

### CODE REVIEW

**Comment by juliangruber** [comment]
@isaacs can you confirm the original results are from a prior version of bash, and not a different flavor or configuration?

**Comment by stevemao** [comment]
Just tested this and @slang800 is correct. change `100644 → 100755` is probably not needed since the `npm-script` is `bash test/generate.sh`

**Comment by stevemao** [comment]
@isaacs Just curious where you got this list? Is it complete? does it need to be updated?

**Comment by isaacs** [comment]
Yeah, i'm not sure.  It must've been from a different bash version or something.  Definitely a bug, since it diverges from the reference implementation, Bash 4.3.

**Comment by stevemao** [comment]
I'll do a PR.

**Comment by stevemao** [comment]
Just note the changed test case wasn't there. There is a change because the test case was duplicated. You probably use the same bash version but missed this use case.

**Comment by isaacs** [comment]
Oh, I see, yes.  Not a bug due to using the wrong bash version, just a missing test case and a regular old-fashioned bug :)

**Pull request closed without merging**
