### PR TITLE
Add npm files filter

### LINKED ISSUE #6: npmignore
Add please `test` to npmignore

### PR DESCRIPTION
**Pull request by TrySound**
fix #6

### CODE REVIEW

**Comment by juliangruber** [comment]
i personally find it usefull to have `node_modules/*/README.md` available, also this will break the published module if we start moving code to `lib/`. Maybe just ignore `test/` as you originally proposed.

**Comment by TrySound** [comment]
@juliangruber https://docs.npmjs.com/files/package.json#files

> Certain files are always included, regardless of settings:
> package.json
> README (and its variants)
> CHANGELOG (and its variants)
> LICENSE / LICENCE

**Comment by TrySound** [comment]
@juliangruber If we start moving code to lib, we can just add `lib` to this list. It supports folders too.

**Comment by juliangruber** [comment]
yeah, but i'll forget to do that ;)

**Comment by TrySound** [comment]
@juliangruber I will watching for this :)

**Comment by TrySound** [comment]
@juliangruber Whitelist is always better then blacklist, I think.

**Comment by TrySound** [comment]
@juliangruber Now I add blacklist, so you can add lib folder without fear.

**Comment by juliangruber** [comment]
awesome, thanks!

**Comment by TrySound** [comment]
@juliangruber Release patch please

**Comment by juliangruber** [comment]
oops, released as 1.1.1

**Comment by TrySound** [comment]
@juliangruber Thanks!

**Pull request merged**
